services:
  mongo:
    image: mongo:5
    container_name: student-mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: student-backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/studentdb
      - PORT=3001
    depends_on:
      - mongo

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3005:3000"
    depends_on:
      - prometheus
